// See https://aka.ms/new-console-template for more information

Console.WriteLine("Hello, World!");
//WriteLine("// NOTE: This file was automatically generated by the CodeGenerator.");
//WriteLine("// Do not alter the contents of this file if you are not extremly");
//WriteLine("// smart. If you find code in here that does not compile you can");
//WriteLine("// comment it out as a workaround and inform Fabi, so he knows he is");
//WriteLine("// not as smart as he thinks and can fix it asap.");